#spring:
#  datasource:
#    username: varerleet
#    password: rencai666..
#    url: jdbc:mysql://182.92.2.51:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/member/*.xml
#  global-config:
#    db-config:
#      id-type: auto  #主键自增
#server:
#  port: 8000

spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: 182.92.2.51 #192.168.200.130
    port: 6379
    password: aa6631656

#设置feign客户端超时时间
ribbon:
  #建立连接
  ReadTimeout:  5000
  #远程调用
  ConnectTimeout: 5000