spring:
  datasource:
    username: varerleet
    password: rencai666..
    url: jdbc:mysql://182.92.2.51:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: redis

  thymeleaf:
    cache: false

  redis:
    host: 182.92.2.51 #192.168.200.130
    port: 6379
    password: aa6631656

  cache:
    type: redis
    redis:
      time-to-live: 3600000 #60 * 60 * 1000


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/product/*.xml
  global-config:
    db-config:
      id-type: auto  #主键自增
server:
  port: 10001

#logging:
#  level:
#    com.scnu.gulimall: debug

#远程调用失败后,服务降级
feign:
  hystrix:
    enabled: true

#自定义线程池配置
gulimall:
  pool:
    core-pool-size: 5
    maximum-pool-size: 20
    keep-alive-time: 10
    queue-size: 10000

