spring:
  datasource:
    username: varerleet
    password: rencai666..
    url: jdbc:mysql://182.92.2.51:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss   #返回值Date转string的时候,添加上,否则日期错误
    time-zone: GMT+8

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss  #请求参数String转Date的时候,添加上,否则报错

  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: 182.92.2.51 #192.168.200.130
    port: 6379
    password: aa6631656

  rabbitmq:
    host: 182.92.2.51
    port: 5672
    username: guest
    password: rencai666..
    virtual-host: /
    publisher-confirms: true #开启发送端消息抵达broker确认
    publisher-returns: true  #发送端消息抵达队列确认
    template:
      mandatory: true  #只要消息没有抵达队列,优先以异步方式回调returnConfirm
    listener:
      simple:
        acknowledge-mode: manual #手动ack


mybatis-plus:
  mapper-locations: classpath:/mapper/order/*.xml
  global-config:
    db-config:
      id-type: auto  #主键自增
server:
  port: 9000



#自定义线程池配置
gulimall:
  pool:
    core-pool-size: 5
    maximum-pool-size: 20
    keep-alive-time: 10
    queue-size: 10000

#feign:
#  hystrix:
#    enabled: true

#设置feign客户端超时时间
ribbon:
  #建立连接
  ReadTimeout:  5000
  #远程调用
  ConnectTimeout: 5000



