spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false
  redis:
    host: 182.92.2.51 #192.168.200.130
    port: 6379
    password: aa6631656

#用于服务降级,使得注解@FeignClient中添加fallback后起作用
feign:
  hystrix:
    enabled: true

