server:
  port: 14000

spring:
  redis:
    host: 182.92.2.51
    password: aa6631656

#自定义线程池配置
gulimall:
  pool:
    core-pool-size: 5
    maximum-pool-size: 20
    keep-alive-time: 10
    queue-size: 10000